# Generated by Django 5.2 on 2025-04-17 16:10

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDetails',
            fields=[
                ('branch_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HubDetails',
            fields=[
                ('hub_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.UUID, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DurationField(default=datetime.timedelta(days=5))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoyDetalis',
            fields=[
                ('boy_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedBranch_del', to='api.branchdetails')),
            ],
        ),
        migrations.AddField(
            model_name='branchdetails',
            name='hub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedHub', to='api.hubdetails'),
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('branch_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedBranch_location', to='api.branchdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Pincodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('branch_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedBranch_pincodes', to='api.branchdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
