# Generated by Django 5.2 on 2025-05-01 20:48

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awbno', models.CharField(max_length=10)),
                ('doc_type', models.CharField(max_length=10)),
                ('pcs', models.IntegerField()),
                ('wt', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='BranchDetails',
            fields=[
                ('branch_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('branchname', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HubDetails',
            fields=[
                ('hub_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('hubname', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InscanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('awbno', models.CharField(max_length=10)),
                ('inscaned_branch_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('inscaned_branch_code', models.CharField(max_length=10)),
                ('tohub_branch_code', models.CharField(max_length=10)),
                ('manifestnumber', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_code', models.CharField(max_length=20)),
                ('vehiclenumber', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2025, 5, 2, 20, 48, 25, 761724))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoyDetalis',
            fields=[
                ('boy_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedBranch_del', to='api.branchdetails')),
            ],
        ),
        migrations.AddField(
            model_name='branchdetails',
            name='hub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedHub', to='api.hubdetails'),
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('branch_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedBranch_location', to='api.branchdetails')),
            ],
        ),
        migrations.CreateModel(
            name='OutscanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awbno', models.CharField(max_length=10)),
                ('manifestnumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.manifestdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Pincodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('branch_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedBranch_pincodes', to='api.branchdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('code_name', models.CharField(max_length=30)),
                ('manifestnumber', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manifestdetails',
            name='vehicle_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle_details'),
        ),
    ]
