# Generated by Django 5.2 on 2025-05-01 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 20, 59, 41, 916843)),
        ),
        migrations.AlterField(
            model_name='manifestdetails',
            name='manifestnumber',
            field=models.CharField(max_length=30),
        ),
    ]
