# Generated by Django 5.2 on 2025-04-17 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customtokenmodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='token',
            field=models.UUIDField(default=uuid.UUID('1437764b-1703-43de-a5f0-4d6d1a454b98'), unique=True),
        ),
    ]
