# Generated by Django 5.2 on 2025-05-01 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customtokenmodel_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 21, 0, 11, 38135)),
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='vehiclenumber',
            field=models.CharField(max_length=10),
        ),
    ]
