# Generated by Django 5.2 on 2025-04-17 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customtokenmodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
