# Generated by Django 5.2 on 2025-05-01 21:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customtokenmodel_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 21, 2, 20, 901732)),
        ),
        migrations.AlterField(
            model_name='manifestdetails',
            name='manifestnumber',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='outscanmodel',
            name='manifestnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manifestdetails'),
        ),
        migrations.AlterField(
            model_name='vehicle_details',
            name='vehiclenumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
