# Generated by Django 5.2 on 2025-04-17 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customtokenmodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 17, 53, 49, 637448, tzinfo=datetime.timezone.utc)),
        ),
    ]
