# Generated by Django 5.2 on 2025-05-01 23:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customtokenmodel_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 23, 59, 41, 539536)),
        ),
        migrations.AlterField(
            model_name='manifestdetails',
            name='vehicle_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle_details'),
        ),
    ]
