# Generated by Django 5.2 on 2025-04-17 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 17, 54, 14, 828671, tzinfo=datetime.timezone.utc)),
        ),
    ]
