# Generated by Django 5.2 on 2025-05-07 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customtokenmodel_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 23, 34, 36, 794862)),
        ),
    ]
