# Generated by Django 5.2 on 2025-04-19 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchdetails',
            old_name='name',
            new_name='branchname',
        ),
        migrations.RenameField(
            model_name='hubdetails',
            old_name='name',
            new_name='hubname',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='firstname',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 7, 18, 25, 954191, tzinfo=datetime.timezone.utc)),
        ),
    ]
