# Generated by Django 5.2 on 2025-04-19 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_name_branchdetails_branchname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='code_name',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 7, 39, 31, 913839, tzinfo=datetime.timezone.utc)),
        ),
    ]
