# Generated by Django 5.2 on 2025-04-19 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userdetails_code_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('awbno', models.CharField(max_length=10)),
                ('inscaned_branch_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 17, 27, 57, 631207, tzinfo=datetime.timezone.utc)),
        ),
    ]
