# Generated by Django 5.2 on 2025-12-24 23:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverdordrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awbno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awbno', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('recievername', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery/')),
                ('reason', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='drs_number',
            field=models.CharField(default='25001001020001', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 29, 23, 29, 20, 920554)),
        ),
        migrations.AlterField(
            model_name='deliveryboydetalis',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedBranch_delboy', to='api.branchdetails'),
        ),
        migrations.AlterField(
            model_name='manifestdetails',
            name='vehicle_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_number', to='api.vehicle_details'),
        ),
        migrations.CreateModel(
            name='DRS',
            fields=[
                ('drsno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=20)),
                ('boycode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedBoy_del', to='api.deliveryboydetalis')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedBranch_del', to='api.branchdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DrsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awbno', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('drsno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LinkedDelivery_number', to='api.drs')),
            ],
        ),
    ]
