# Generated by Django 5.2 on 2025-04-19 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_inscan_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscan',
            new_name='InscanModel',
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 17, 53, 13, 16844, tzinfo=datetime.timezone.utc)),
        ),
    ]
