# Generated by Django 5.2 on 2025-04-21 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_inscan_inscanmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awbno', models.CharField(max_length=10)),
                ('doc_type', models.CharField(max_length=10)),
                ('pcs', models.IntegerField()),
                ('wt', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 4, 48, 52, 597506, tzinfo=datetime.timezone.utc)),
        ),
    ]
