# Generated by Django 5.0.12 on 2025-12-27 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_deliverdordrs_deliverydetails_userdetails_drs_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 18, 27, 56, 817713)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='drs_number',
            field=models.CharField(default='250<django.db.models.fields.CharField>020001', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='manifestnumber',
            field=models.CharField(default='250<django.db.models.fields.CharField>010001', max_length=20),
        ),
    ]
