# Generated by Django 5.2 on 2025-04-23 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bookingdetails_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 3, 55, 39, 528074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inscanmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
