# Generated by Django 5.0.12 on 2025-12-27 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customtokenmodel_expired_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='branch_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='deliveryboydetalis',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='drs',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='pincodes',
            name='branch_code',
        ),
        migrations.AddField(
            model_name='deliveryboydetalis',
            name='code',
            field=models.CharField(default='0001', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drs',
            name='code',
            field=models.CharField(default='001', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincodes',
            name='code',
            field=models.CharField(default='001', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 21, 48, 29, 754972)),
        ),
    ]
