# Generated by Django 5.0.12 on 2025-12-27 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_branch_code_locations_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 21, 55, 38, 465374)),
        ),
        migrations.AlterField(
            model_name='drsdetails',
            name='drsno',
            field=models.CharField(max_length=20),
        ),
    ]
