# Generated by Django 5.0.12 on 2025-12-27 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_customtokenmodel_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 21, 58, 59, 867488)),
        ),
        migrations.AlterField(
            model_name='drs',
            name='drsno',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drsdetails',
            name='drsno',
            field=models.CharField(max_length=30),
        ),
    ]
