# Generated by Django 5.0.12 on 2025-12-27 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_customtokenmodel_expired_at_alter_drs_drsno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdetails',
            name='hub',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 22, 5, 47, 622514)),
        ),
        migrations.AlterField(
            model_name='drs',
            name='boycode',
            field=models.CharField(max_length=20),
        ),
    ]
