# Generated by Django 5.0.12 on 2025-12-27 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_branchdetails_hub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 23, 5, 1, 157725)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
