# Generated by Django 5.0.12 on 2025-12-27 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customtokenmodel_expired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='location_code',
            field=models.CharField(default='th001', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 23, 9, 59, 862618)),
        ),
    ]
