# Generated by Django 5.0.12 on 2025-12-29 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awbno', models.CharField(max_length=10)),
                ('doc_type', models.CharField(max_length=10)),
                ('pcs', models.IntegerField()),
                ('wt', models.DecimalField(decimal_places=3, max_digits=5)),
                ('sendername', models.CharField(max_length=50)),
                ('senderaddress', models.TextField()),
                ('senderphonenumber', models.CharField(max_length=10)),
                ('recievername', models.CharField(max_length=50)),
                ('recieveraddress', models.TextField()),
                ('recieverphonenumber', models.CharField(max_length=10)),
                ('destination_location_code', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('booked_code', models.CharField(max_length=20)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 12, 29, 31, 463058)),
        ),
    ]
