# Generated by Django 5.0.12 on 2025-12-29 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_bookingdetails_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='date',
            field=models.DateField(default='2025-12-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='recievernumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 14, 17, 31, 812219)),
        ),
    ]
