# Generated by Django 5.0.12 on 2026-01-02 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_deliverydetails_date_deliverydetails_recievernumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='destination_location_code',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='destination_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booked_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='contents',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='doc_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='pcs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='recieveraddress',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='recievername',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='recieverphonenumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='senderaddress',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='sendername',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='senderphonenumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='wt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 7, 14, 42, 19, 951505)),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='drs_number',
            field=models.CharField(default='260<django.db.models.fields.CharField>020001', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='manifestnumber',
            field=models.CharField(default='260<django.db.models.fields.CharField>010001', max_length=20),
        ),
    ]
