# Generated by Django 5.0.12 on 2026-01-03 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_bookingdetails_destination_location_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 8, 1, 34, 6, 835242)),
        ),
    ]
