# Generated by Django 5.0.12 on 2026-01-03 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='booked_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='destination_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='doc_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='pcs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='wt',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 8, 21, 35, 43, 897065)),
        ),
        migrations.AlterField(
            model_name='deliveryboydetalis',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
