# Generated by Django 5.0.12 on 2026-01-09 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_bookingdetails_booked_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 14, 13, 6, 15, 460269)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='drs_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='manifestnumber',
            field=models.CharField(max_length=20),
        ),
    ]
