# Generated by Django 5.0.12 on 2026-01-09 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_version_alter_customtokenmodel_expired_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('build', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_id', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='version',
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 14, 16, 1, 41, 749383)),
        ),
    ]
