# Generated by Django 5.0.12 on 2026-01-09 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_apprelease_delete_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 14, 16, 11, 34, 462954)),
        ),
    ]
