# Generated by Django 5.0.12 on 2026-01-10 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 15, 15, 59, 27, 189576)),
        ),
    ]
