# Generated by Django 5.0.12 on 2026-01-11 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_bookingdetails_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchdetails',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='hubdetails',
            name='pincode',
        ),
        migrations.AddField(
            model_name='branchdetails',
            name='incharge_name',
            field=models.CharField(default='testname', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hubdetails',
            name='incharge_name',
            field=models.CharField(default='testnamesssssssd', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hubdetails',
            name='region',
            field=models.CharField(default='south', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hubdetails',
            name='state',
            field=models.CharField(default='ap', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincodes',
            name='pincode_type',
            field=models.CharField(default='std', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 10, 41, 5, 207224)),
        ),
    ]
