# Generated by Django 5.0.12 on 2026-01-21 21:24

import api.views.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_branchdetails_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtokenmodel',
            name='expired_at',
            field=models.DateTimeField(default=api.views.utils.token_expiry),
        ),
    ]
