# Generated by Django 5.0.12 on 2026-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_customtokenmodel_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='refernce_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
