# Generated by Django 5.0.12 on 2026-02-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_bookingdetails_refernce_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildPieceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awbno', models.CharField(max_length=10)),
                ('child_no', models.CharField(max_length=10)),
            ],
        ),
    ]
