# Generated by Django 5.0.12 on 2026-02-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_childpiecedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childpiecedetails',
            name='child_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
