# Generated by Django 5.0.12 on 2026-02-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_childpiecedetails_child_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='drs',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
