# Generated by Django 5.0.12 on 2026-02-15 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_childpiecedetails_child_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#1976d2', max_length=7)),
                ('secondary_color', models.CharField(default='#424242', max_length=7)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_list', to='api.companyprofile'),
        ),
    ]
