# Generated by Django 5.0.12 on 2026-03-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_drs_document_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='drs_number',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='manifestnumber',
        ),
        migrations.AddField(
            model_name='branchdetails',
            name='drs_counter',
            field=models.CharField(default='0001', max_length=4),
        ),
        migrations.AddField(
            model_name='branchdetails',
            name='manifest_counter',
            field=models.CharField(default='0001', max_length=4),
        ),
    ]
