# Generated by Django 6.0.6 on 2026-06-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_userdetails_drs_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='eway_bill_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='branchdetails',
            name='drs_counter',
            field=models.CharField(default='001', max_length=4),
        ),
        migrations.AlterField(
            model_name='branchdetails',
            name='manifest_counter',
            field=models.CharField(default='001', max_length=4),
        ),
    ]
