# Generated by Django 6.0.6 on 2026-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_bookingdetails_eway_bill_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='booking_type',
            field=models.CharField(default='retail', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='client_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
